name: .NET Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish -c Release -r linux-x64 --self-contained /p:PublishSingleFile=true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: bin/Release/net8.0/linux-x64/publish/
